$:.unshift(File.join(__dir__, '..', '..', '..', 'spec'))
$:.unshift(File.join(__dir__, '..', '..', '..', 'lib'))

require 'allure_config'
require 'json'
require 'erb'
require 'optparse'
require 'msfenv'

module ReportGeneration
  class SupportMatrix
    def initialize(data)
      @data = data
    end

    def generation_date
      Time.now.strftime("%FT%T")
    end

    def table
      sorted_sessions = @data.fetch(:sessions, []).sort_by { |session| session[:session_type] }
      sorted_session_names = sorted_sessions.map do |session|
        session[:session_type]
      end

      all_commands = Rex::Post::Meterpreter::CommandMapper.get_command_names

      # Group into buckets, and priortize sort order
      extension_names = [
        # MVP Meterpreter
        "core",
        "stdapi",

        # Remaining
        "sniffer",
        "extapi",
        "kiwi",
        "python",
        "unhook",
        "appapi",
        "winpmem",
        "powershell",
        "lanattacks",
        "priv",
        "incognito",
        "peinjector",
        "espia",
        "android",
      ]

      ordered_commands = all_commands.sort_by do |command|
        command_prefix = command.split("_").first
        sort_index = extension_names.index(command_prefix)

        sort_index
      end

      # Map session type to supported commands. i.e. { osx: { command_name_1: true } }
      sessions_to_supported_commands_hash = sorted_sessions.each_with_object({}) do |session, hash|
        session_type = session[:session_type]
        # Map command name to its availability
        supported_command_map = session[:commands].each_with_object({}) do |command, map|
          command_name = command[:name]
          map[command_name] = true
        end
        hash[session_type] = supported_command_map
      end

      columns = [""] + sorted_session_names
      rows = extension_names.map do |extension_name|
        extension_commands = ordered_commands.select { |command| command.start_with?(extension_name) }

        command_rows = extension_commands.map do |command|
          session_supported_cells = sessions_to_supported_commands_hash.map do |(_session, compatibility)|
            compatibility.include?(command)
          end

          [command] + session_supported_cells
        end
        extension_coverage = sessions_to_supported_commands_hash.map do |(_session, compatibility)|
          implemented_count = extension_commands.select { |command| compatibility.include?(command) }.size
          total_count = extension_commands.size
          percentage = ((implemented_count.to_f / total_count.to_f) * 100).to_i

          "#{percentage}%"
        end

        {
          heading: [extension_name] + extension_coverage,
          values: command_rows
        }
      end

      {
        columns: columns,
        rows: rows
      }
    end

    def get_binding
      binding
    end
  end

  def self.extract_data(options)
    if options[:allure_data]
      results_directory = options[:allure_data]
      test_result_files = Dir["**/*-result.json", base: results_directory]
      meterpreter_compatibility_results = test_result_files.filter_map do |test_result_file|
        path = File.join(results_directory, test_result_file)
        json = JSON.parse(File.read(path), symbolize_names: true)

        compatibility_attachment = json.fetch(:attachments, [])
                                   .find { |attachment| attachment[:name] == 'available commands' }
        next unless compatibility_attachment

        compatibility_attachment_path = File.join(File.dirname(path), compatibility_attachment[:source])
        JSON.parse(File.read(compatibility_attachment_path), symbolize_names: true)
      end

      aggregated_data = meterpreter_compatibility_results.each_with_object({}) do |data, aggregate|
        aggregate[:sessions] ||= []
        aggregate[:sessions] += data[:sessions]
      end

      aggregated_data
    else
      data_path = options.fetch(:data_path)
      data = JSON.parse(File.read(data_path), symbolize_names: true)

      data
    end
  end

  def self.generate(options)
    data = self.extract_data(options)

    template = File.read(File.join(File.dirname(__FILE__),'template.erb'))
    renderer = ERB.new(template, trim_mode: '-')
    support_matrix = SupportMatrix.new(data)

    result = renderer.result(support_matrix.get_binding)
    STDOUT.write(result)
  end
end

if $PROGRAM_NAME == __FILE__
  options = {}
  options_parser = OptionParser.new do |opts|
    opts.banner = "Usage: #{File.basename(__FILE__)} [options]"

    opts.on '-h', '--help', 'Help banner.' do
      return print(opts.help)
    end

    opts.on('--allure-data [path]', 'Use allure as the data source') do |allure_data|
      allure_data ||= AllureRspec.configuration.results_directory
      options[:allure_data] = allure_data
    end

    opts.on('--data-path', 'The path to the report generated by scripts/resource/meterpreter_compatibility.rc') do |data_path|
      options[:skip_migration] = data_path
    end
  end
  options_parser.parse!

  ReportGeneration.generate(options)
end
