name: Acceptance

#concurrency:
#  group: ${{ github.ref }}-${{ github.workflow }}
#  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  # TODO: Write required for gh-pages write access
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  pull_request:
    branches:
      - '*'
#  schedule:
#    - cron: '0,5,10,15,25,30,35,45,50,55 * * * *'

jobs:
  # Run all test individually, note there is a separate job for aggregating the test results
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
#          - macos-10.15
          - windows-2016
          - windows-2019
          - windows-2022
#          - ubuntu-18.04
#        meterpreter:
#          - { name: python, runtime_version: 2.7 }
#          - { name: python, runtime_version: 3.6 }
#          - { name: python, runtime_version: 3.8 }
#          - { name: java, runtime_version: 8 }
#          - { name: php, runtime_version: 5.3 }
#          - { name: php, runtime_version: 7.4 }
          # Broken:
#          - { name: php, runtime_version: 8.1 }
#          - { name: windows_meterpreter }
#          - { name: mettle }
#        ruby:
#          - 3.0.2
#        include:
#          - { meterpreter: { name: windows_meterpreter }, os: windows-2016 }
#          - { meterpreter: { name: windows_meterpreter }, os: windows-2022 }
#        exclude:
#          - { meterpreter: { name: mettle }, os: windows-2019 }
#          # Broken:
#          - { meterpreter: { name: php, runtime_version: 5.3 }, os: windows-2019 }
#          # Skip mac/ubuntu windows_meterpreter test runs
#          - { meterpreter: { name: windows_meterpreter }, os: macos-10.15 }
#          - { meterpreter: { name: windows_meterpreter }, os: ubuntu-18.04 }
#
    runs-on: ${{ matrix.os }}

    timeout-minutes: 25

    env:
      RAILS_ENV: test
      METERPRETER: ${{ matrix.meterpreter.name }}
      METERPRETER_RUNTIME_VERSION: ${{ matrix.meterpreter.runtime_version }}

    name: ${{ matrix.meterpreter.name }} ${{ matrix.meterpreter.runtime_version }} ${{ matrix.os }}
    steps:
      - name: test smb
        run: |
          Get-SmbServerConfiguration
          Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol

          echo "log path"

          whoami
          whoami /all
          echo 'net user'
          net user

          echo 'net accounts'
          net accounts

          echo 'net user add'

          # Disable password policy, so we can set passwords to 'password' without needing extra complexity
          secedit /export /cfg c:\secpol.cfg
          (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
          rm -force c:\secpol.cfg -confirm:$false

          # Disable user access control, so we can run psexec remotely
          # reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
          reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1 /f

          net user TestingAccount password /ADD /Y
          # net user TestingAccount /delete

          echo 'adding to local group'
          net localgroup administrators TestingAccount /ADD

          echo 'viewing net accounts'
          net accounts

          echo 'viewing testingaccount'
          net user TestingAccount

          exit

#      - name: Install system dependencies (Linux)
#        if: runner.os == 'Linux'
#        run: sudo apt-get install libpcap-dev graphviz
#
#      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#        if: ${{ matrix.meterpreter.name == 'php' }}
#        with:
#          php-version: ${{ matrix.meterpreter.runtime_version }}
#          tools: none
#
#      - name: Set up Python
#        if: ${{ matrix.meterpreter.name == 'python' }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.meterpreter.runtime_version }}
#
#      - uses: actions/setup-java@v2
#        if: ${{ matrix.meterpreter.name == 'java' }}
#        with:
#          distribution: temurin
#          java-version: ${{ matrix.meterpreter.runtime_version }}
#
      - name: Install system dependencies (Windows)
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          REM pcap dependencies
          powershell -Command "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} ; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip', 'C:\Windows\Temp\WpdPack_4_1_2.zip')"

          choco install 7zip.installServerCertificateValidationCallback
          7z x "C:\Windows\Temp\WpdPack_4_1_2.zip" -o"C:\"
          REM mv C:\WpdPack\Lib\x64\Packet.lib C:\WpdPack\Lib\
          REM mv C:\WpdPack\Lib\x64\wpcap.lib C:\WpdPack\Lib\

          REM php configuration - enable sockets, otherwise php reverse shells fail on AF_INET constants
          php -r "file_put_contents(php_ini_loaded_file(), PHP_EOL . 'extension=sockets' . PHP_EOL, FILE_APPEND);"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        env:
          BUNDLE_WITHOUT: "coverage development pcap"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
#
##      - name: debugging
##        if: always()
##        run: |
##          gem install pcaprub -v '0.13.1' --verbose
#
#      # Takes 5-6 minutes, potentially cacheable
##      - name: Install postgres (Windows)
##        if: runner.os == 'Windows'
##        shell: bash
##        run: |
##          choco install postgresql12 --force --params '/Password:postgres'
##          echo 'C:\Program Files\PostgreSQL\12\bin' >> $GITHUB_PATH
##          echo 'C:\Program Files\PostgreSQL\12\lib' >> $GITHUB_PATH
##          echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
##
##      - name: Create database
##        run: |
##          cp config/database.yml.github_actions config/database.yml
##          bundle env
##          bundle exec rake --version
##          bundle exec rake db:create
##          bundle exec rake db:migrate
##          # fail build if db/schema.rb update is not committed
##          git diff --exit-code db/schema.rb
#
      - name: acceptance
        run: |
          bundle exec rspec './spec/acceptance/smb_spec.rb' --color --format Fivemat --format AllureRspecFormatter
#          bundle exec rspec './spec/acceptance/meterpreter_spec.rb' --color --format Fivemat --format AllureRspecFormatter

#
#      - name: Archive results
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          # Provide a unique artifact for each matrix os, otherwise race conditions can lead to corrupt zips
#          name: raw-data-${{ matrix.meterpreter.name }}-${{ matrix.meterpreter.runtime_version }}-${{ matrix.os }}
#          path: tmp/allure-raw-data
#
#  # Generate a final report from the previous test results
#  report:
#    name: Generate report
#    needs: test
#    runs-on: ubuntu-18.04
#    if: always()
#
#    steps:
#      - name: Install system dependencies (Linux)
#        if: runner.os == 'Linux'
#        run: sudo apt-get install libpcap-dev graphviz
#
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Ruby
#        env:
#          BUNDLE_WITHOUT: "coverage development pcap"
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#          bundler-cache: true
#
#      - uses: actions/download-artifact@v2
#        id: download
#        if: always()
#        with:
#          # Note: Not specifying a name will download all artifacts from the previous workflow jobs
#          path: raw-data
#
#      - name: allure generate
#        if: always()
#        run: |
#          export VERSION=2.17.2
#
#          curl -o allure-$VERSION.tgz -Ls https://github.com/allure-framework/allure2/releases/download/$VERSION/allure-$VERSION.tgz
#          tar -zxvf allure-$VERSION.tgz -C .
#
#          ./allure-$VERSION/bin/allure generate ${{steps.download.outputs.download-path}}/* -o ./allure-report
#          bundle exec ruby spec/acceptance/support_matrix/generate_report.rb --allure-data ${{steps.download.outputs.download-path}} > ./allure-report/matrix.html
#
#      - name: archive results
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: final-report
#          path: |
#            ./allure-report
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: ./allure-report
