name: Acceptance

on:
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  pull_request:
    branches:
      - '*'

jobs:
  # Run all test individually, note there is a separate job for aggregating the test results
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - windows-2019
          - ubuntu-18.04
        ruby:
          - 2.7

    runs-on:  ${{ matrix.os }}

    timeout-minutes: 25

    env:
      RAILS_ENV: test

    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    steps:
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install libpcap-dev graphviz

      - name: Install system dependencies (Windows)
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          powershell -Command "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} ; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip', 'C:\Windows\Temp\WpdPack_4_1_2.zip')"
          choco install 7zip.installServerCertificateValidationCallback
          7z x "C:\Windows\Temp\WpdPack_4_1_2.zip" -o"C:\"
          mv C:\WpdPack\Lib\x64\Packet.lib C:\WpdPack\Lib\
          mv C:\WpdPack\Lib\x64\wpcap.lib C:\WpdPack\Lib\

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        env:
          BUNDLE_WITHOUT: "coverage development pcap"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      # Takes 5-6 minutes, see if this can be cached
#      - name: Install postgres (Windows)
#        if: runner.os == 'Windows'
#        shell: bash
#        run: |
#          choco install postgresql12 --force --params '/Password:postgres'
#          echo 'C:\Program Files\PostgreSQL\12\bin' >> $GITHUB_PATH
#          echo 'C:\Program Files\PostgreSQL\12\lib' >> $GITHUB_PATH
#          echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
#
#      - name: Create database
#        run: |
#          cp config/database.yml.github_actions config/database.yml
#          bundle env
#          bundle exec rake --version
#          bundle exec rake db:create
#          bundle exec rake db:migrate
#          # fail build if db/schema.rb update is not committed
#          git diff --exit-code db/schema.rb

      - name: acceptance
        run: |
          bundle exec rspec spec/acceptance --color --format Fivemat --format AllureRspecFormatter

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          # Provide a unique artifact for each matrix os, otherwise race conditions can lead to corrupt zips
          name: raw-data-${{ matrix.os }}
          path: tmp/allure-raw-data

  # Generate a final report from the previous test results
  report:
    name: Generate report
    needs: test
    runs-on: ubuntu-18.04
    if: always()

    steps:
      - uses: actions/download-artifact@v2
        id: download
        if: always()
        with:
          # Note: Not specifying a name will download all artifacts from the previous workflow jobs
          path: raw-data

      - name: allure generate
        if: always()
        run: |
          export VERSION=2.17.2

          curl -o allure-$VERSION.tgz -Ls https://github.com/allure-framework/allure2/releases/download/$VERSION/allure-$VERSION.tgz
          tar -zxvf allure-$VERSION.tgz -C .

          ./allure-$VERSION/bin/allure generate ${{steps.download.outputs.download-path}}/* -o ./allure-report

      - name: archive results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: final-report
          path: |
            ./allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report
